// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyvpeoqrniscbgdvonby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5dnBlb3FybmlzY2JnZHZvbmJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MDE5MjksImV4cCI6MjA2ODM3NzkyOX0.dxv9SaOT4OIYWDqV5tLAH5lkZ2GPfwlRtc_s8KIs1jY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});